version: '3.8'

services:
  bookstore-app:
    image: "${IMAGE_NAME}"
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    env_file:
      - ./docker/app/.env
    ports:
      - "8080:8080"
    depends_on:
      - db
    command: ["/usr/local/bin/app/wait-for-postgres.sh", "db", "/usr/local/bin/app/init.sh"]


  db:
    container_name: pg_container
    image: postgres:alpine
    restart: always
    env_file:
      - ./docker/app/.env
    ports:
      - "5432:5432"
    volumes:
      - ./pg_data:/var/lib/postgresql/data/