version: '3.8'

services:
  bookstore-app:
    image: "${IMAGE_NAME}"
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    env_file:
      - ./docker/app/.env
    ports:
      - "8080:8080"
    depends_on:
      - db


  db:
    container_name: pg_container
    image: postgres:alpine
    restart: always
    env_file:
      - ./docker/app/.env
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - ./pg_data:/var/lib/postgresql/data/