apiVersion: v1
kind: Service
metadata:
  name: bookstore-app
  namespace: bookstore
  labels:
    app: bookstore-app
spec:
  type: NodePort
  ports:
    - port: 8001
      targetPort: 8080
      nodePort: 30080
      name: http
  selector:
    app: bookstore-app