name: cloudy-bookstore-CICD

on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - master
      - develop
      
defaults:
  run:
    working-directory: .      

jobs:
  # The “build” workflow
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up GO 1.16
        uses: actions/setup-go@v2
        with:
          go-version: '1.16.0'
      - name: Install dependencies
        run: |
          go version
          go get -u golang.org/x/lint/golint
      - name: Run build
        run: go build -o bookstore.exe ./cmd/bookstore/main.go
      - name: Run vet & lint
        run: |
          go vet ./cmd/bookstore/main.go
          golint ./cmd/bookstore/main.go
  # The "deploy" workflow
  deploy:
    runs-on: ubuntu-latest

    needs: [ build ]
    if: ${{ github.ref == 'refs/heads/master' && github.event_name == 'push' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./docker/app/Dockerfile
          push: true
          tags: abhinav812/cloudy-bookstore:latest
          
