name: cloudy-bookstore-heroku

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

defaults:
  run:
    working-directory: .

jobs:
  heroku-deploy:
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/develop' && github.event_name == 'push' }} # deploys only from develop branch
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build, Push and Deploy to Heroku
        id: heroku
        uses: techmmunity/docker-heroku-deploy@v1.0.0
        with:
          context: ./
          email: ${{ secrets.HEROKU_EMAIL }}
          api_key: ${{ secrets.HEROKU_API_KEY }}
          app_name: ${{ secrets.HEROKU_APP_NAME }}
          dockerfile_path: ./docker/app
